### ISSUE TITLE
Unable to jump sometimes after jumping over the bridge

### ISSUE THREAD

**Issue by Ntraxalon** [seylorx1/des203#1]
Steps to reproduce: 
Load into the tutorial scene
Lined up with bridge to the castle area
Moved forward and jumped over the bridge

Expected result:
Clear the bridge and controller be fully functional

Actual Result:
Cleared the bridge and jump button no longer functioned

**Comment by seylorx1** [comment]
Fixed this in 23b1051afb829e49ee02ee522f2314219d42630f
